// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_tabl_Course : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tabl_Course));
        
        string IMigrationMetadata.Id
        {
            get { return "202304201417179_add_tabl_Course"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
